config/routes.rb
Rails.application.routes.draw do
  get 'kcals/new'

  #get 'chart_sample/index'

  resources :meetings
  resources :posts
  resources :graff
  resources :kcals
  #4devise_for :kcal
  
  get 'mypage/show'
  
  get 'graff/show'
  
  get 'fat/show'
  
  get 'kcals/index'
  
  #get 'kcals/new'
  
  #post 'meetings'
  
  get 'gift/show'
 
  get 'meetings/index'
  
  root 'pages#index'
  devise_for :users
   
   #get 'pages/help'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
   resources :users
   
   get    '/login',  to: 'sessions#new'
   post   '/login',  to:'sessions#create'
   delete '/logout', to:'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
end

app/models/graff.rb
class Graff < ApplicationRecord
    def index
        @meeting = Meeting.group_by_day(:name).count
    end
end

app/models/kcal.rb
class Kcal < ApplicationRecord
validates :weight1, presence: true
validates :height1, presence: true
validates :age1, presence: true
  
  
  def bmr1_keisan
    (13.397 * weight1 + 4.799 * height1 - 5.677 * age1 + 88.362)
  end
  
  def tdee1_keisan
    (bmr1_keisan * 1.3)
  end
end

app/models/meeting.rb
class Meeting < ApplicationRecord
     VALID_NAME_REGEX =0-9
     VALID_FAT_REGEX =0-9
    validates :name, presence: true,length: {maximum: 2}
    validates :fat, presence: true,length: {maximum: 2}
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  #devise :database_authenticatable, :registerable,:recoverable, :rememberable, :validatable
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    VALID_PASSWORD_REGEX =/\A[a-zA-Z0-9]+\z/
   
   validates :name, presence: true,length: {maximum: 15}
   validates :email, presence: true
   validates :password, presence: true, length: { minimum: 8, maximum: 32}
   
   has_secure_password
   
end

app/controllers/fat_controller.rb
class FatController < ApplicationController
   def index
   end
end

app/controllers/gift_controller.rb
class GiftController < ApplicationController
   def index
      Product.order("RANDOM()").first
   end
   
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  before_action :set_meeting, only: [:show, :edit, :update, :destroy]

  # GET /meetings
  # GET /meetings.json
  def index
    @meetings = Meeting.all
  end

  # GET /meetings/1
  # GET /meetings/1.json
  def show
  end

  # GET /meetings/new
  def new
    @meeting = Meeting.new
  end

  # GET /meetings/1/edit
  def edit
  end

  # POST /meetings
  # POST /meetings.json
  def create
    @meeting = Meeting.new(meeting_params)

    respond_to do |format|
      if @meeting.save
        format.html { redirect_to @meeting, notice: 'Meeting was successfully created.' }
        format.json { render :show, status: :created, location: @meeting }
      else
        format.html { render :new }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /meetings/1
  # PATCH/PUT /meetings/1.json
  def update
    respond_to do |format|
      if @meeting.update(meeting_params)
        format.html { redirect_to @meeting, notice: 'Meeting was successfully updated.' }
        format.json { render :show, status: :ok, location: @meeting }
      else
        format.html { render :edit }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meetings/1
  # DELETE /meetings/1.json
  def destroy
    @meeting.destroy
    respond_to do |format|
      format.html { redirect_to meetings_url, notice: 'Meeting was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_meeting
      @meeting = Meeting.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def meeting_params
      params.require(:meeting).permit(:name,:fat, :start_time,:menu,:cc,:ci)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
   def current_user
      @current_user ||= User.find_by(id:session[:user_id])
   end
   
   def loggend_in?
      !current_user.nil?
   end
end

app/helpers/chart_sample_helper.rb
module ChartSampleHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/fat_helper.rb
module FatHelper
end

app/helpers/gift_helper.rb
module GiftHelper
end

app/helpers/graff_helper.rb
module GraffHelper
end

app/helpers/kcals_helper.rb
module KcalsHelper
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/helpers/mypage_helper.rb
module MypageHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/meetings/_form.html.haml
= form_for @meeting do |f|
  - if @meeting.errors.any?
    #error_explanation
      %h2= "#{pluralize(@meeting.errors.count, "error")} prohibited this meeting from being saved:"
      %ul
        - @meeting.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :体重
    = f.text_field :name,placeholder: '例）70'
    kg
  .field
    = f.label :体脂肪
    = f.text_field :fat,placeholder: '例）20' 
    ％
    .field
    = f.label :メニュー
    = f.text_field :menu,placeholder: 'ベンチプレス' 
    .field
    = f.label :消費カロリー
    = f.text_field :cc,placeholder: '例）300' 
    Kcal
    .field
    = f.label :摂取カロリー
    = f.text_field :ci,placeholder: '例）400' 
    Kcal
  .field
    = f.label :記録時間
    = f.datetime_select :start_time
  .actions
    = f.submit 'Save'

app/views/meetings/edit.html.haml
%h1 編集

= render 'form'

= link_to 'Show', @meeting

= link_to 'Back', meetings_path

app/views/meetings/index.html.haml
!!!

%p#idnotice=  notice 
%h1.text-center カレンダー
%table
  %thead
    %tr
      %th 体重｜
      %th 体脂肪｜
      %th メニュー　　｜
      %th 摂取カロリー｜
      %th 消費カロリー｜
      %th 時間
    =link_to 'マイページ', mypage_show_path, class: 'btn btn-default btn-black'
    =link_to 'グラフ', graff_show_path, class: 'btn btn-default btn-black'
    = link_to 'カロリー計算',kcals_new_path, class: 'btn btn-default btn-black'
  %tbody
    - @meetings.each do |meeting|
      %tr
        %td= meeting.name
        %td= meeting.fat
        %td= meeting.menu
        %td= meeting.ci
        %td= meeting.cc
        %td= meeting.start_time.strftime('%Y年-%m月-%d日 %H:%M:%S')
        %td= link_to '閲覧', meeting
        %td= link_to '編集', edit_meeting_path(meeting.id)
        %td= link_to '削除',meeting_path(meeting.id), method: :delete, data: { confirm: 'Are you sure?' }
  %br/
        
        
=month_calendar events: @meetings do |date, meetings|
  =date.day
  =link_to '記入', new_meeting_path, class:"btn btn-sm btn-outline-secondary"

app/views/meetings/new.html.haml
%h1 新規作成

= render 'form'

= link_to 'Back', meetings_path

app/views/meetings/show.html.haml
%p#notice= notice

%p
  %b 体重:
  = @meeting.name
%p
  %b 体脂肪:
  = @meeting.fat
%p
  %b Start time:
  = @meeting.start_time.strftime('%Y-%m-%d %H:%M')

= link_to 'Edit', edit_meeting_path(@meeting)
\|
= link_to 'Back', meetings_path