config/routes.rb
Rails.application.routes.draw do
  get 'kcals/new'

  #get 'chart_sample/index'

  resources :meetings
  resources :posts
  resources :graff
  resources :kcals
  #4devise_for :kcal
  
  get 'mypage/show'
  
  get 'graff/show'
  
  get 'fat/show'
  
  get 'kcals/index'
  
  #get 'kcals/new'
  
  #post 'meetings'
  
  get 'gift/show'
 
  get 'meetings/index'
  
  root 'pages#index'
  devise_for :users
   
   #get 'pages/help'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
   resources :users
   
   get    '/login',  to: 'sessions#new'
   post   '/login',  to:'sessions#create'
   delete '/logout', to:'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
end

app/models/graff.rb
class Graff < ApplicationRecord
    def index
        @meeting = Meeting.group_by_day(:name).count
    end
end

app/models/kcal.rb
class Kcal < ApplicationRecord
validates :weight1, presence: true
validates :height1, presence: true
validates :age1, presence: true
  
  
  def bmr1_keisan
    (13.397 * weight1 + 4.799 * height1 - 5.677 * age1 + 88.362)
  end
  
  def tdee1_keisan
    (bmr1_keisan * 1.3)
  end
end

app/models/meeting.rb
class Meeting < ApplicationRecord
     VALID_NAME_REGEX =0-9
     VALID_FAT_REGEX =0-9
    validates :name, presence: true,length: {maximum: 2}
    validates :fat, presence: true,length: {maximum: 2}
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  #devise :database_authenticatable, :registerable,:recoverable, :rememberable, :validatable
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    VALID_PASSWORD_REGEX =/\A[a-zA-Z0-9]+\z/
   
   validates :name, presence: true,length: {maximum: 15}
   validates :email, presence: true
   validates :password, presence: true, length: { minimum: 8, maximum: 32}
   
   has_secure_password
   
end

app/controllers/fat_controller.rb
class FatController < ApplicationController
   def index
   end
end

app/controllers/gift_controller.rb
class GiftController < ApplicationController
   def index
      Product.order("RANDOM()").first
   end
   
end

app/controllers/mypage_controller.rb
class MypageController < ApplicationController
  #before_action :authenticatable_user!
  
  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
   def current_user
      @current_user ||= User.find_by(id:session[:user_id])
   end
   
   def loggend_in?
      !current_user.nil?
   end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/fat_helper.rb
module FatHelper
end

app/helpers/gift_helper.rb
module GiftHelper
end

app/helpers/graff_helper.rb
module GraffHelper
end

app/helpers/kcals_helper.rb
module KcalsHelper
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/helpers/mypage_helper.rb
module MypageHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/mypage/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Recodiet
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield
    :javascript
      $(function(){
      $(".alert").fadeOut(5000);
      });

app/views/mypage/show.html.haml
.top-hero-wrapper.text-center
   .cotainer.top-hero-container
      .h1.text-white Recodiet
      .logo.text-white トレーニングお疲れ様です
      .row
         .col-md-offset-3.col-md-2
            =link_to 'カレンダー', meetings_path, class: 'btn btn-default btn-white'
         .col-md-2
            =link_to 'グラフ', graff_show_path, class: 'btn btn-default btn-white'
         .col-md-3
            = link_to 'カロリー計算',kcals_new_path, class: 'btn btn-default btn-white'
/=link_to '体脂肪グラフ', fat_show_path, class: 'btn btn-default btn-black'
/=link_to 'ご褒美', gift_show_path,class: 'btn btn-default btn-black'